[package]
name = "node"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
[dependencies]
rust.workspace = true
tokio.workspace = true
napi = { version = "3", features = ["tokio_rt"] }
napi-derive = "3"
[lib]
test = false
crate-type = ["cdylib", "rlib"]
[build-dependencies]
napi-build = "2"
